### ISSUE TITLE
Make Administrative panel adaptive

### ISSUE THREAD

**Issue by dimayakovlev** [dimayakovlev/getsimple-extended-cms#45]
Administrative panel is usable on devices with screens width more than 960px + scrollbar + browser borders.

Have no plans yet to adapt Administrative panel for mobiles but want to make it wider on desktops.

**Comment by dimayakovlev** [comment]
Now gap between `#maincontent` and `#sidebar` is: 960px - 690px - 225px = 45px. Want to reduce it to 20px:

```css
.bodycontent {
    display: flex;
    flex-flow: row nowrap;
    justify-content: space-between;
    align-items: flex-start;
    gap: 20px;
}
#maincontent {
    /* width: 690px; */
    text-align: left;
    flex: 1;
}
#sidebar {
    width: 225px;
    position: sticky;
    top: 20px;
}
```

Need to make `#sidebar` wider?
